<template>
  <div class="h-full overflow-hidden p-8 bg-[var(--color-bg)] flex flex-col gap-6 animate-fade-in">
    <div><h1 class="text-[26px] font-semibold text-[var(--color-text)] tracking-tight">{{ t('chat.title') }}</h1><p class="text-[14px] text-muted mt-1">{{ t('chat.subtitle') }}</p></div>
    <div v-if="!aiEnabled" class="card p-5 border border-amber-400/30 bg-amber-400/5 flex items-center justify-between gap-5"><div><p class="font-medium text-[var(--color-text)]">{{ t('chat.notEnabledTitle') }}</p><p class="text-[13px] text-muted mt-1">{{ t('chat.notEnabledDescription') }}</p></div><button @click="router.push('/settings')" class="btn-primary text-[13px] shrink-0">{{ t('chat.openSettings') }}</button></div>
    <section class="flex-1 min-h-0 flex gap-4 overflow-hidden">
      <aside class="card w-60 shrink-0 flex flex-col overflow-hidden p-3">
        <button @click="startNewChat" :disabled="sending" class="btn-primary text-[13px] w-full mb-4 disabled:opacity-50">+ {{ t('chat.newChat') }}</button>
        <div class="flex items-center justify-between px-1 mb-2"><p class="text-[11px] font-semibold uppercase tracking-wider text-muted">{{ showingArchived ? t('chat.archived') : t('chat.recentChats') }}</p><button @click="toggleArchived" class="text-[11px] text-[var(--color-accent)] hover:opacity-80">{{ showingArchived ? t('chat.showActive') : t('chat.showArchived') }}</button></div>
        <div class="flex-1 overflow-y-auto space-y-1"><p v-if="conversations.length === 0" class="px-2 py-3 text-[12px] text-muted">{{ showingArchived ? t('chat.noArchived') : t('chat.noChats') }}</p><button v-for="chat in conversations" :key="chat.id" @click="openChat(chat.id)" class="w-full rounded-lg px-2.5 py-2 text-left transition-colors" :class="activeChatId === chat.id ? 'bg-[var(--color-accent)]/12 text-[var(--color-text)]' : 'hover:bg-[var(--color-hover)] text-muted'"><span class="block truncate text-[12px] font-medium">{{ chat.title }}</span><span class="mt-0.5 block text-[10px] opacity-70">{{ formatDate(chat.updatedAtUtc) }}</span></button></div>
        <div v-if="activeChatId !== null" class="mt-3 space-y-2"><button @click="archiveCurrentChat" :disabled="sending" class="w-full text-[12px] text-muted hover:text-[var(--color-text)] disabled:opacity-50">{{ showingArchived ? t('chat.unarchive') : t('chat.archive') }}</button><button @click="deleteCurrentChat" :disabled="sending" class="w-full text-[12px] text-red-400 hover:text-red-300 disabled:opacity-50">{{ t('chat.deleteChat') }}</button></div>
        <button v-if="conversations.length" @click="deleteAllChats" :disabled="sending" class="mt-3 w-full text-[12px] text-red-400 hover:text-red-300 disabled:opacity-50">{{ t('chat.deleteAll') }}</button>
      </aside>
      <div class="card flex-1 min-w-0 flex flex-col overflow-hidden">
        <div ref="messageList" class="flex-1 overflow-y-auto p-5 space-y-4">
          <div v-if="messages.length === 0" class="h-full min-h-[260px] flex flex-col items-center justify-center text-center px-6"><div class="w-11 h-11 rounded-xl flex items-center justify-center bg-[var(--color-accent)]/10 text-[var(--color-accent)] mb-4"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/><path d="M8 10h.01M12 10h.01M16 10h.01"/></svg></div><p class="font-medium text-[var(--color-text)]">{{ t('chat.emptyTitle') }}</p><p class="text-[13px] text-muted mt-1 max-w-md">{{ t('chat.emptyDescription') }}</p><div class="flex flex-wrap justify-center gap-2 mt-5"><button v-for="suggestion in suggestions" :key="suggestion" @click="useSuggestion(suggestion)" class="text-left rounded-lg border border-app px-3 py-2 text-[12px] text-muted hover:text-[var(--color-text)] hover:bg-[var(--color-hover)] transition-colors">{{ suggestion }}</button></div></div>
          <div v-for="(message, index) in messages" :key="index" class="flex" :class="message.role === 'user' ? 'justify-end' : 'justify-start'"><div class="max-w-[78%] rounded-xl px-4 py-3 text-[13px] leading-relaxed" :class="message.role === 'user' ? 'bg-[var(--color-accent)] text-white whitespace-pre-wrap' : 'bg-[var(--color-hover)] text-[var(--color-text)]'"><MarkdownContent v-if="message.role === 'assistant'" :content="message.content" /><template v-else>{{ message.content }}</template></div></div>
          <div v-if="sending" class="flex justify-start"><div class="rounded-xl px-4 py-3 text-[13px] bg-[var(--color-hover)] text-muted">{{ t('chat.thinking') }}</div></div>
        </div>
        <form @submit.prevent="sendMessage" class="border-t border-app p-4"><label class="flex items-center gap-2 mb-3 text-[12px] text-muted cursor-pointer select-none"><input v-model="includeActivity" type="checkbox" class="accent-[var(--color-accent)]" :disabled="sending || !aiEnabled" /><span>{{ t('chat.includeActivity') }}</span><span class="text-[11px] opacity-75">{{ t('chat.activityPrivacy') }}</span></label><div class="flex gap-3 items-end"><textarea v-model="draft" rows="2" :disabled="sending || !aiEnabled || showingArchived" :placeholder="t('chat.placeholder')" @keydown.enter.exact.prevent="sendMessage" class="input flex-1 resize-none py-2.5" /><button type="submit" :disabled="!draft.trim() || sending || !aiEnabled || showingArchived" class="btn-primary h-[42px] px-4 disabled:opacity-50 disabled:cursor-not-allowed">{{ sending ? t('chat.sending') : t('chat.send') }}</button></div><p v-if="showingArchived" class="text-[12px] text-muted mt-2">{{ t('chat.archivedReadonly') }}</p><p v-if="error" class="text-[12px] text-red-400 mt-2">{{ error }}</p></form>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { archiveChatConversation, chatWithAi, createChatConversation, deleteAllChatConversations, deleteChatConversation, getChatConversations, getChatMessages, saveChatMessage, type AiChatMessage, type ChatConversation } from '@/services/tauri'
import { useSettingsStore } from '@/stores/settings'
import MarkdownContent from '@/components/MarkdownContent.vue'
const { t, locale } = useI18n(); const router = useRouter(); const settingsStore = useSettingsStore()
const messages = ref<AiChatMessage[]>([]); const conversations = ref<ChatConversation[]>([]); const activeChatId = ref<number | null>(null); const showingArchived = ref(false); const draft = ref(''); const sending = ref(false); const error = ref(''); const includeActivity = ref(true); const messageList = ref<HTMLElement | null>(null)
const aiEnabled = computed(() => settingsStore.settings?.aiEnabled ?? false); const suggestions = computed(() => [t('chat.suggestionFocus'), t('chat.suggestionBreaks'), t('chat.suggestionRoutine')])
onMounted(async () => { if (!settingsStore.settings) await settingsStore.fetchSettings(); await loadConversations() })
async function loadConversations() { conversations.value = await getChatConversations(showingArchived.value) }
function startNewChat() { activeChatId.value = null; messages.value = []; draft.value = ''; error.value = '' }
async function toggleArchived() { if (sending.value) return; showingArchived.value = !showingArchived.value; startNewChat(); await loadConversations() }
async function openChat(id: number) { if (sending.value) return; activeChatId.value = id; error.value = ''; messages.value = (await getChatMessages(id)).map(({ role, content }) => ({ role, content })); await scrollToBottom() }
async function archiveCurrentChat() { if (activeChatId.value === null || sending.value) return; await archiveChatConversation(activeChatId.value, !showingArchived.value); startNewChat(); await loadConversations() }
async function deleteCurrentChat() { if (activeChatId.value === null || sending.value || !window.confirm(t('chat.deleteConfirm'))) return; await deleteChatConversation(activeChatId.value); startNewChat(); await loadConversations() }
async function deleteAllChats() { if (sending.value || !window.confirm(t('chat.deleteAllConfirm'))) return; await deleteAllChatConversations(); startNewChat(); await loadConversations() }
function useSuggestion(suggestion: string) { draft.value = suggestion }; function chatTitle(content: string) { return content.replace(/\s+/g, ' ').slice(0, 56) || t('chat.untitled') }; function formatDate(date: string) { return new Intl.DateTimeFormat(locale.value, { day: 'numeric', month: 'short' }).format(new Date(date)) }
async function scrollToBottom() { await nextTick(); if (messageList.value) messageList.value.scrollTop = messageList.value.scrollHeight }
async function sendMessage() { const content = draft.value.trim(); if (!content || sending.value || !aiEnabled.value || showingArchived.value) return; error.value = ''; try { if (activeChatId.value === null) { const chat = await createChatConversation(chatTitle(content)); activeChatId.value = chat.id; conversations.value.unshift(chat) }; const conversationId = activeChatId.value; messages.value.push({ role: 'user', content }); draft.value = ''; sending.value = true; await saveChatMessage(conversationId, 'user', content); await scrollToBottom(); const response = await chatWithAi(messages.value, includeActivity.value, locale.value); messages.value.push({ role: 'assistant', content: response }); await saveChatMessage(conversationId, 'assistant', response); await loadConversations() } catch (e: any) { error.value = e?.message || String(e) } finally { sending.value = false; await scrollToBottom() } }
</script>
